title: Skepticism Today
subtitle: Skeptical. Critical. Topical.
summary: A topical skeptical podcast from New Zealand
description: Skepticism Today is an hour long monthly skeptical podcast created by Dell Mitchell, Mark Honeychurch, Simon McAuliffe and Tim Atkin
url: https://skepticism.today
logo: /assets/images/Logo-iTunes.png
permalink: /:episode
remote_theme: jonaharagon/jekyll-bootstrap-theme
timezone: Pacific/Auckland
author:
  name: Mark Honeychurch
  email: mark@honeychurch.org
google:
  analytics: G-Q9S8F62XT2
permalink: /:title
archive: skepticism-today
