#theme: jekyll-theme-cayman
remote_theme: chrisrhymes/bulma-clean-theme
timezone: Pacific/Auckland
google_analytics: UA-51344487-1
podcast:
  title: Skepticism Today
  owner: Mark Honeychurch
  email: mark@honeychurch.org
  url: https://skepticism.today
  album_art: /assets/Logo-iTunes.png
  category: Skepticism
  subcategory_one: Science
  subcategory_two: Critical Thinking
  explicit: false
  author: Mark Honeychurch
  description: A topical skeptical podcast from New Zealand.
  summary: Skepticism Today is an hour long monthly skeptical podcast created by Dell Mitchell, Mark Honeychurch, Simon McAuliffe and Tim Atkin.
  subtitle: Skeptical. Critical. Topical.
