title: Skepticism Today
subtitle: Skeptical. Critical. Topical.
summary: A topical skeptical podcast from New Zealand
description: Skepticism Today is an hour long monthly skeptical podcast created by Dell Mitchell, Mark Honeychurch, Simon McAuliffe and Tim Atkin
url: https://skepticism.today
permalink: /:episode
remote_theme: jonaharagon/jekyll-bootstrap-theme
timezone: Pacific/Auckland
author:
  name: Mark Honeychurch
  email: mark@honeychurch.org
google:
  analytics:
permalink: /:title
podcast:
  title: Skepticism Today
  owner: Mark Honeychurch
  email: mark@honeychurch.org
  url: https://skepticism.today
  album_art: /assets/Logo-iTunes.png
  category: Skepticism
  subcategory_one: Science
  subcategory_two: Critical Thinking
  explicit: false
  author: Mark Honeychurch
  description:
  summary: .
  subtitle:
